import jsPDF from 'jspdf';
import { IntakeSummary } from '../types/intake';

export function exportIntakePDF(summary: IntakeSummary): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Header background
  doc.setFillColor(15, 23, 42); // slate 900
  doc.rect(0, 0, 210, 45, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('VOICE INTAKE SUMMARY REPORT', 14, 20);

  doc.setFontSize(10);
  doc.setFont('Helvetica', 'normal');
  doc.setTextColor(148, 163, 184); // slate 400
  doc.text(`Generated on ${summary.generatedAt} | Session ID: ${summary.sessionId}`, 14, 30);
  doc.text(`Target Buyer Category: ${summary.clientInfo.buyerType.toUpperCase()}`, 14, 37);

  // Client Details Section
  doc.setFontSize(14);
  doc.setFont('Helvetica', 'bold');
  doc.setTextColor(99, 102, 241); // Indigo
  doc.text('CLIENT PROFILE', 14, 58);

  doc.setLineWidth(0.5);
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 61, 196, 61);

  doc.setFontSize(10);
  doc.setFont('Helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Name:', 14, 70);
  doc.text('Company:', 14, 77);
  doc.text('Email:', 110, 70);
  doc.text('Phone:', 110, 77);

  doc.setFont('Helvetica', 'normal');
  doc.text(summary.clientInfo.name || 'N/A', 35, 70);
  doc.text(summary.clientInfo.company || 'N/A', 35, 77);
  doc.text(summary.clientInfo.email || 'N/A', 125, 70);
  doc.text(summary.clientInfo.phone || 'N/A', 125, 77);

  // Project Scope & Budget
  doc.setFontSize(14);
  doc.setFont('Helvetica', 'bold');
  doc.setTextColor(99, 102, 241);
  doc.text('PROJECT SCOPE & BUDGET', 14, 93);
  doc.line(14, 96, 196, 96);

  doc.setFontSize(10);
  doc.setFont('Helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Estimated Budget:', 14, 105);
  doc.text('Timeline:', 110, 105);

  doc.setFont('Helvetica', 'normal');
  doc.text(summary.estimatedBudget, 48, 105);
  doc.text(summary.timeline, 128, 105);

  doc.setFont('Helvetica', 'bold');
  doc.text('Scope Overview:', 14, 115);
  doc.setFont('Helvetica', 'normal');
  const splitScope = doc.splitTextToSize(summary.projectScope, 180);
  doc.text(splitScope, 14, 122);

  let currentY = 122 + (splitScope.length * 5) + 8;

  // Key Requirements
  doc.setFontSize(14);
  doc.setFont('Helvetica', 'bold');
  doc.setTextColor(99, 102, 241);
  doc.text('KEY REQUIREMENTS', 14, currentY);
  doc.line(14, currentY + 3, 196, currentY + 3);
  currentY += 10;

  doc.setFontSize(10);
  doc.setFont('Helvetica', 'normal');
  doc.setTextColor(30, 41, 59);
  summary.keyRequirements.forEach((req) => {
    doc.text(`• ${req}`, 18, currentY);
    currentY += 6;
  });

  currentY += 6;

  // Action Items
  doc.setFontSize(14);
  doc.setFont('Helvetica', 'bold');
  doc.setTextColor(99, 102, 241);
  doc.text('RECOMMENDED ACTION ITEMS', 14, currentY);
  doc.line(14, currentY + 3, 196, currentY + 3);
  currentY += 10;

  doc.setFontSize(10);
  doc.setFont('Helvetica', 'normal');
  doc.setTextColor(30, 41, 59);
  summary.actionItems.forEach((item) => {
    doc.text(`[ ] ${item}`, 18, currentY);
    currentY += 6;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Confidential - Generated by VoiceIntake AI Edge Router', 14, 285);

  doc.save(`Intake-Summary-${summary.clientInfo.company || 'Client'}-${Date.now()}.pdf`);
}

export function exportIntakeJSON(summary: IntakeSummary): void {
  const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(summary, null, 2));
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute("href", dataStr);
  downloadAnchor.setAttribute("download", `intake-summary-${Date.now()}.json`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}
